"""init

Revision ID: 69157c3916cc
Revises: 
Create Date: 2024-07-14 13:34:14.642965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69157c3916cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_collection', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('feature_collection')

    op.create_table('geo',
    sa.Column('Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('geometry', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('individual_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('csv_uuid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Observed Depth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('geo', schema=None) as batch_op:
        batch_op.create_index('idx_geo_geometry', ['geometry'], unique=False, postgresql_using='gist')

    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
